name = "neo-budget"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "BUDGET_KV"
id = "1fe0d7d49247405abdaa08a5286bca7d"
preview_id = "1fe0d7d49247405abdaa08a5286bca7d"
